import "./globals.css";

export const metadata = {
  title: "Next authenticator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
